POST http://localhost:3000/medicine

{
    "brandName": "Brand Name",
    "owner": "alalalaj",
    "genericName": "Generic Name",
    "metrology": {
        "weight": 20,
        "measurement": "mg"
    }
}

###
PUT http://localhost:3000/medicine/5fa685b5a301888f24a821fb

{
    "brandName": "Brand Name",
    "owner": "alalah",
    "genericName": "Generic Name",
    "metrology": {
        "weight": 10,
        "measurement": "mg"
    }
}